name: CI

on:
  push:
    branches:
      - Domain-Setup  # Trigger on pushes to the feature branch
  pull_request:
    branches:
      - Domain-Setup # Trigger on PRs targeting the feature branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Java (JDK 11 recommended for Kotlin/Android)
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          distribution: 'adoptium'
          java-version: '1.8'

      # Step 3: Cache Gradle dependencies
      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle/wrapper, ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # Step 4: Build and run tests
      - name: Build and test the project
        run: ./gradlew clean build

      # Step 5: Run Detekt linting
      - name: Run detekt (Linting)
        run: ./gradlew detekt
